language: java
jdk:
- openjdk12
notifications:
  email: false
cache:
  directories:
  - "$HOME/.m2"
before_install:
- openssl aes-256-cbc -K $encrypted_c4a11a42d40f_key -iv $encrypted_c4a11a42d40f_iv
  -in deploy/marmoush.com.gpg.enc -out deploy/marmoush.com.gpg -d
- gpg --import deploy/marmoush.com.gpg

deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml -P travis_deployment
  on:
    branch: master
    tags: true
branches:
  only:
  - master
  - "/v\\d+\\.\\d+\\.\\d+/"
env:
  global:
  - secure: ZYchX1ztFdqqeNdi6VvLOuxD+HW7+YpsLLlFwI7nIgqDe0Oor44GBhGXXa1h2LsNKaTlbg6b6m4X0mkRyq1Xox5TK4f72+qshLzgTkLbebHLRU6oICMBVlYvmNRB9zhh4Ksn0FHxt+97XQ0NtvZ/sKd0DRG8U2+9Q5mjLS0kXWXmRHeCN38jTkF+Y+OAg2/w+dRjflWzMc4qpN5aDsEnxRXs51ZQZ4Q14NaAZPUQI3TUhpEIapq5RZnq9cSNTFPsukgw6A4cphUlJOhtFXcE4JXGJtW++FbXkc0sI5jG5Oc2G4JkoYPKeJEN0ZBZOXDdrwTG4DutOCfSqbr30wDAQsRIDmCbSDzae4G02hSASb7qLe/HqrWmNiu8t/ailpR/OrVa5ofyd+0qnE5cuJ6LwhXFYyJ0VHlKoc3ZGWJJ60uVyfP7P9+htju4LhiocnS/GfPftV7FD7fIurNtBZQBrfq8GU84Gx3szKtaTJx2bs/yNJPa3Hz2p+i3ISE3+n71yIx1yDY42PHxPRsutZIr/rhKzJ8lEoR3IX9VHDvM7200w1Sns2+BgzM1fnSS5K6tsXyo86SmI0VO30KdXYoWfD3307tSW2EaSGoT99WJTLUk2lyWUQ23x9WUCKzhyPC/8BnTq9x6dyrB17SGp4+bxO657mT+m93bN34Hr5tBM4U=
  - secure: R2648NNStov1fcwIUVMQ/5gGMdlZcKPIkUJFkfVAtKVyG1Z6UtHPk2RIWrD/CTGq6cg9Ylm376Nka6n/rN+2zX5Nq8qw55i2iMWtPSjDTS3IPwVdEF9I67kagu3PICedFq2OdW9Hy5NBj5bKADm76zIuP1/QBUZaMWb/cUi9zfhC/SN93QbjqV6YnPAl9ZIgVh2QaLM1mxS/SI+ZMHQWpAaT6J+JeQ3G6BAfbxEJhQ4OwWDuvTvKA7R4kPuJyYj4VD4nxTYrxuPyylLHdrWgtsNXbo5PBh6cjLOy3StWhVbb9T5l+TvbO3f+PamWeVt+qaIZRJuf9XroP+AG3fe5zKZeQjxXTYO6tOrePYFPrMpTuuehySp6dxfes48q4Fjqn7CZuwc0kgynIPGREw8FgsZM+LR8QgvY1Ur0/qf8cxE1f7FkcVSaTX2qJLicf6fEMzuYpVsLXNc5r/vosca3g2DVMR6Vy+W6Pv9Ix9DKlnc3tdz0PCeDdB4znKIk+8YUsOnMwL5rcHf8mDVU2fclmSTOgcr+Xh1gfgn8fGr/Fccla7sTuSm5fA89xx/VA2/8Wscip9RbnjbGj1dCiCmcX02n5NpsgUfCf2vJWfQibfyya0yF+LUnpQEzBCqJLarDPKnTPzFXcI4IGG0uNKxlQNQ5068ceXM+M+hPbh8W3zQ=
  - secure: UYe2mxx7Un8wVqyldCKicJEfooEDrBaefetYUjv/R9qOR2e8XOahItK0hen6I3xa9QClZVPoJNbKmlWUpOv8JgEOSFLMRy8Mh4b+1QEbIREiusBzhud0NFDVLNVYa5gjGK5oFOXU7IsVLoQ12GqmLWL+hh7DglMJXRVPAjiCQpUT8HK5xU6zWC/YCZgauvQw+ZGfaKyhZByHHDB4iSACO7KcNlBhPXhGP4iCMvlNBSc08gZxTZB/rdHcPIUJARiRpK+gDGoVmxBDpLKekbbyE9RZxlAF7zuENh57QgMtVeLBF42ax9ESnMj3bKYcqX64jyICnI58d6LZRk89QZHszJ0gnLYf8jxDiRM3YFaZJnIxVbD7fq6hcItxFrwSMXACmYFOimPUlox9rM/ukWvS9OIMzzPHMOBPNKr/c72eawIIzolEDDN+4hxEmVsmjAFBwtmXD0+xvOOMjyia9km1oftiXEnnVMiTqPGRsn/QrTTMkxpp3euALR1RCUurbIMDXh+jH4Ih232PdbKSKkASzoaoT5wsYWLaY6V17NrkGAQfHaWdDB1DUYmEhZSfe3sW75OKAnleeOC7rP2E1utWjbyuJa8KtHa/G31UoBNn1M7VQeD0e56Pp/bEDKF1efwZ8So/FFgI3qmUOEcxoW69PsKrbI3AAYayhnHZu+fmGAU=
  - secure: hbZNqJ/9BFVigFbw+isWEgN/ATPr+7brTUTMWHXD8cle0VYJn7VmME9TpEWKsMSZHiBkX4ekQOF9Hqt9MzauTCkUdGrzIcy15RwkLA1h5Uu/okSBWGoo3knwBrw6CPg+Oz1fQZ/oIVsmbzLiprKnwGJtSm6wmfWv0xSy6ms9lg+/CbKkkr12Xn531vyODxsjvhIFQqqEXbrZdSrej7E9g+z+YGfisJ4I2ZNxZimBhZtzHgzv9fuAPDWS3VjVafEFdJs2RCqLXMWf9CzrMSZ8tuosE1CMjoQgqfWjZzP4tp0UKtXy6cwL1gsuXONWbMl1wKPA5syzWArc8eOxX2KMJ2rSvTL1TuOjrnVs5NOHQvfbctsF+4ZhOQneQoDOoTkpjlRjr+hQsFvYs4981JcFguDTNNxx2AJGrkknVfuaJx9nTjpGeNjW7S4ePoqwZ7lH70eoM04g9ifrEQnQ3BG55dCAKcGMHC8DgaVZKlBqFnUqiWTWTCvUw5phrb8NtSLhTSgs7FbL2L0+8vryS6l9i2iRyKA+1efAjSmVWZDvlhQQ+qyjotvwHFp2yLqjc2oXRNj53QwucMt7du109h1OpubSt47LyRc+OMIHcsTpKk+OxJ8PB56MDhV3NlsGQ8NWnBYtyU/8ykB+AB6wCfqjvE/xkewpiWtiT/Grk+ayh8s=
