name: Build

on:
  push:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '16'
      - name: check java
        run: |
          java --version
          mvn --version
          echo $JAVA_HOME    
      - name: Maven Install
        run: mvn install


