name: Publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  Publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - name: Publish to Maven
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          DEPLOY_DIR: ".github/deploy"
        run: |
          GPG_TTY=$(tty || echo "")
          export GPG_TTY
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.FILE_ENCRYPTION_PASSWORD }}" --output $DEPLOY_DIR/marmoush.com.gpg $DEPLOY_DIR/marmoush.com.gpg.gpg
          gpg --import --no-tty --batch --yes $DEPLOY_DIR/marmoush.com.gpg
          mvn deploy --settings $DEPLOY_DIR/maven-settings.xml -P cloud_deployment

      - name: Build image
        run: docker build . --tag memoriaio/jbom:${GITHUB_SHA::8}

      - name: Log into registry
        if: github.event_name == 'push'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker tag memoriaio/jbom:${GITHUB_SHA::8} ${GITHUB_REPOSITORY,,}:latest
          docker push memoriaio/jbom:${GITHUB_SHA::8}
          docker push memoriaio/jbom:latest
