name: Publish

on:
  push:
    tags:
      - v*.*.*

jobs: 
  Publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '16'
      - name: check java
        run: |
          java --version
          mvn --version
          echo $JAVA_HOME        
      - name: Publish to Maven
        timeout-minutes: 10
        run: mvn --batch-mode deploy -Psonar_cloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}